import { Request, Response, NextFunction } from "express";
import { db, apiKeysTable } from "@workspace/db";
import { eq } from "drizzle-orm";

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      apiKeyUserId?: string;
    }
  }
}

function extractKey(req: Request): string | undefined {
  const header = req.headers["x-api-key"];
  if (typeof header === "string" && header.trim()) return header.trim();

  const auth = req.headers["authorization"];
  if (typeof auth === "string" && auth.startsWith("Bearer ")) {
    const token = auth.slice(7).trim();
    if (token) return token;
  }

  // Query param fallback — convenient for quick testing / simple HTTP
  // clients, but the header form is what we document and recommend.
  const q = req.query["key"] ?? req.query["api_key"];
  if (typeof q === "string" && q.trim()) return q.trim();

  return undefined;
}

// Protects the public API surface (/api/v1/*). Requires a valid, active
// key from the api_keys table — generated by signed-in users on the
// website's API Keys page. This is separate from the website's own
// internal /api/music/youtube/* routes, which stay open for guest
// browsing/search.
export async function requireApiKey(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  const key = extractKey(req);

  if (!key) {
    res.status(401).json({
      error:
        "API key required. Generate one from your account's API Keys page, then send it as an X-API-Key header (or Authorization: Bearer <key>).",
    });
    return;
  }

  try {
    const [record] = await db
      .select()
      .from(apiKeysTable)
      .where(eq(apiKeysTable.key, key))
      .limit(1);

    if (!record || !record.active) {
      res.status(401).json({ error: "Invalid or revoked API key" });
      return;
    }

    req.apiKeyUserId = record.userId;

    // Best-effort usage tracking — never block the request on this.
    db.update(apiKeysTable)
      .set({ lastUsedAt: new Date() })
      .where(eq(apiKeysTable.id, record.id))
      .catch((err: unknown) => {
        req.log?.warn({ err }, "Failed to update API key lastUsedAt");
      });

    next();
  } catch (err) {
    req.log?.error({ err }, "API key validation failed");
    res
      .status(503)
      .json({ error: "API key validation is temporarily unavailable" });
  }
}
